
package com.webservice.student;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Student", targetNamespace = "http://server")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Student {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getNameReturn", targetNamespace = "http://server", partName = "getNameReturn")
    public String getName(
        @WebParam(name = "id", targetNamespace = "http://server", partName = "id")
        String id);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "studentQueryReturn", targetNamespace = "http://server", partName = "studentQueryReturn")
    public String studentQuery();

    /**
     * 
     * @param logArg
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "studentLoginReturn", targetNamespace = "http://server", partName = "studentLoginReturn")
    public boolean studentLogin(
        @WebParam(name = "logArg", targetNamespace = "http://server", partName = "logArg")
        LogArg logArg);

    /**
     * 
     * @param regArg
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "studentRegisterReturn", targetNamespace = "http://server", partName = "studentRegisterReturn")
    public boolean studentRegister(
        @WebParam(name = "regArg", targetNamespace = "http://server", partName = "regArg")
        RegArg regArg);

    /**
     * 
     * @param selcetArg
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "selectCourseReturn", targetNamespace = "http://server", partName = "selectCourseReturn")
    public boolean selectCourse(
        @WebParam(name = "selcetArg", targetNamespace = "http://server", partName = "selcetArg")
        SelcetArg selcetArg);

    /**
     * 
     * @param dropArg
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "dropCourseReturn", targetNamespace = "http://server", partName = "dropCourseReturn")
    public boolean dropCourse(
        @WebParam(name = "dropArg", targetNamespace = "http://server", partName = "dropArg")
        DropArg dropArg);

    /**
     * 
     * @param nothing
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryAllCourseReturn", targetNamespace = "http://server", partName = "queryAllCourseReturn")
    public String queryAllCourse(
        @WebParam(name = "nothing", targetNamespace = "http://server", partName = "nothing")
        int nothing);

    /**
     * 
     * @param studentId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "queryStudentCourseReturn", targetNamespace = "http://server", partName = "queryStudentCourseReturn")
    public String queryStudentCourse(
        @WebParam(name = "student_id", targetNamespace = "http://server", partName = "student_id")
        String studentId);

    /**
     * 
     * @param chanPassArg
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "changeStudentPasswordReturn", targetNamespace = "http://server", partName = "changeStudentPasswordReturn")
    public boolean changeStudentPassword(
        @WebParam(name = "chanPassArg", targetNamespace = "http://server", partName = "chanPassArg")
        ChanPassArg chanPassArg);

}
